# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

source 'https://gitee.com/kingly09/KYSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!

target 'FaceDetectionDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'KYFaceCompare', '~> 0.1.3'
  # Pods for FaceDetectionDemo

  target 'FaceDetectionDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FaceDetectionDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
