# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'FaceDetectionDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Reachability', '~> 3.2'
  pod 'AFNetworking', '~> 3.1.0'

  # Pods for FaceDetectionDemo

  target 'FaceDetectionDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FaceDetectionDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
